---
abstract: 'JavaScript code generation from Perl.'
author:
  - 'Kang-min Liu  C<< <gugod@gugod.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  JE: 0.021
  Test::Class: 0
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: JavaScript::Writer
name: JavaScript-Writer
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Accessor::Fast: 0
  JSON::Syck: 0
  perl: 5.8.0
  self: 0.32
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/gugod/javascript-writer
version: 0.3.1
